### ISSUE TITLE
Add chance to being able to run from monsters in a room

### ISSUE THREAD

**Issue by instrangeland** [jlachniet/GenDungeon#21]
Right now, there is no restriction on simply leaving a room immediately (or so it seems.) You can walk into a room, grab the gold, and leave without having to fight the monster. I think it would work better if there's a "run chance" or something when you leave a room with a monster, perhaps based on how close they are to you?

**Comment by jlachniet** [comment]
When you walk into a room to get something, you can be seen by monsters and attacking on the following turn, so it is not possible to walk in and take items without at least a chance of being hit.
